### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by selandy** [gch1p/alsa-volume-monitor#1]
I've tried using this from the post here: [https://awesome.naquadah.org/wiki/Volume_control_and_display](https://awesome.naquadah.org/wiki/Volume_control_and_display), but I still haven't managed to get it working...

Could you please write a little bit more detailed README for total beginners like me? I'm trying to configure Ubuntu 16.04 with Awesome WM.

I've cloned this on my computer and tried the make command and first got:
`Package alsa was not found in the pkg-config search path.`

So after longer search, I've found that I'm missing the package _libasound2-dev_

After installing it and trying again, this is what I'm getting:

> gcc `pkg-config --libs alsa dbus-1` main.o -o alsa-volume-monitor
> main.o: In function `notify':
> main.c:(.text+0x32): undefined reference to`dbus_message_new_signal'
> main.c:(.text+0x79): undefined reference to `dbus_connection_send'
> main.c:(.text+0xae): undefined reference to`dbus_connection_flush'
> main.c:(.text+0xba): undefined reference to `dbus_message_unref'
> main.o: In function`open_ctl':
> main.c:(.text+0x10c): undefined reference to `snd_ctl_open'
> main.c:(.text+0x148): undefined reference to`snd_ctl_subscribe_events'
> main.c:(.text+0x17a): undefined reference to `snd_ctl_close'
> main.o: In function`check_event':
> main.c:(.text+0x1c9): undefined reference to `snd_ctl_event_sizeof'
> main.c:(.text+0x205): undefined reference to`snd_ctl_event_sizeof'
> main.c:(.text+0x22c): undefined reference to `snd_ctl_read'
> main.c:(.text+0x246): undefined reference to`snd_ctl_event_get_type'
> main.c:(.text+0x25d): undefined reference to `snd_ctl_event_elem_get_mask'
> main.o: In function`monitor':
> main.c:(.text+0x2f2): undefined reference to `snd_ctl_poll_descriptors'
> main.c:(.text+0x336): undefined reference to`snd_ctl_poll_descriptors_revents'
> main.c:(.text+0x366): undefined reference to `snd_ctl_close'
> main.o: In function`main':
> main.c:(.text+0x3e5): undefined reference to `dbus_error_init'
> main.c:(.text+0x3f6): undefined reference to`dbus_bus_get'
> main.c:(.text+0x406): undefined reference to `dbus_error_is_set'
> main.c:(.text+0x433): undefined reference to`dbus_error_free'
> main.c:(.text+0x45e): undefined reference to `dbus_bus_request_name'
> main.c:(.text+0x46a): undefined reference to`dbus_error_is_set'
> main.c:(.text+0x497): undefined reference to `dbus_error_free'
> collect2: error: ld returned 1 exit status
> Makefile:9: recipe for target 'main' failed
> make: **\* [main] Error 1

Do you have any idea what I might be doing wrong?

**Comment by gch1p** [comment]
Hi, @selandy!
I'm going to install Ubuntu 16.04 on VirtualBox and try to build the app on it. So far I have only tested it on Gentoo, which is the distro I'm using. I will write then.

**Comment by gch1p** [comment]
I updated the Makefile. It should work now. Thanks.

**Comment by selandy** [comment]
Now it works perfectly!
Thank you very much! :+1:
